# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('active', models.NullBooleanField()),
                ('login', models.CharField(max_length=64, unique=True)),
                ('company_id', models.IntegerField()),
                ('partner_id', models.IntegerField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('create_uid', models.IntegerField()),
                ('share', models.NullBooleanField()),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('action_id', models.IntegerField(blank=True, null=True)),
                ('password_crypt', models.CharField(blank=True, max_length=200, null=True)),
                ('alias_id', models.IntegerField()),
                ('chatter_needaction_auto', models.NullBooleanField()),
                ('sale_team_id', models.IntegerField(blank=True, null=True)),
                ('target_sales_done', models.IntegerField(blank=True, null=True)),
                ('target_sales_won', models.IntegerField(blank=True, null=True)),
                ('target_sales_invoiced', models.IntegerField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('role_in_org', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('is_deleted', models.NullBooleanField()),
                ('is_prime', models.NullBooleanField()),
                ('user_name', models.CharField(max_length=64, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'res_users',
            },
        ),
    ]
